blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hello/', views.hello_world_view),
]

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('prog_lang.urls')),
    path('', include('relation_db.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prog_lang/urls.py
from django.urls import path
from . import views

app_name='yaziki'

urlpatterns = [
    path('prog_lang/', views.ProgLangListView.as_view(), name='yaizki_programmirovanie'),
    path('prog_lang/<int:id>/', views.ProgLangDetailView.as_view()),
    path('prog_lang/<int:id>/delete/', views.DeleteProgLangView.as_view()),
    path('prog_lang/<int:id>/update/', views.UpdateProgLangView.as_view()),

    path("create_prog_lang/", views.CreateProgLangView.as_view(), name='sozdat_blog'),

    path('search/', views.SeachView.as_view()),
]

relation_db/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    path('all_cars/', views.relation_db)
]

relation_db/models.py
from django.db import models

# many:many
class Tag(models.Model):
    name = models.CharField(max_length=100)


    def __str__(self):
        return self.name
    
# мы добавили многое многому в общую модельку
# общая модель
class NumberCar(models.Model):
    nameCar = models.CharField(max_length=100, default='Lexus GX 570')
    number_Car = models.CharField(max_length=15, default='..KG....')
    tags = models.ManyToManyField(Tag, null=True)

    def __str__(self):
        return f'{self.nameCar} ------- {',' .join(i.name for i in self.tags.all() )}'
    

# 1:1  
class DocumentCar(models.Model):
    choice_car = models.OneToOneField(NumberCar, on_delete=models.CASCADE, related_name='car')
    document = models.CharField(max_length=100)

    def __str__(self):
        return self.document

# 1:many

class Review(models.Model):
    MARKS = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    choice_car = models.ForeignKey(NumberCar, on_delete=models.CASCADE, related_name='review')
    marks = models.CharField(max_length=100, choices=MARKS, default='5')
    text = models.CharField(max_length=100, default='good car')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Марка:{self.choice_car} - Оценка:{self.marks} - Коммент:{self.text}'
    
    

relation_db/views.py
from django.shortcuts import render
from . import models

def relation_db(request):
    if request.method == 'GET':
        number_car = models.NumberCar.objects.all()
        return render(
            request,
            'relation_db.html',
            {
                'number_car': number_car
            }
        )

templates/confirm_delete.html
<h1>Вы действительно хотите удалить язык - {{ prog_lang_id.title }}</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">Да</button>
</form>
    <button><a href="/prog_lang/" style="text-decoration: none;">Нет</a></button>

templates/create_prog_lang.html
<center>
    <h1>Добавить язык програмирование</h1>
    <form action="{% url 'yaziki:sozdat_blog' %}" method="post" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{ form.as_p }}

        <button type="simbit">Добавить</button>

    </form>
</center>

templates/login.html
<center>
    <h1>Авторизация</h1>
    <form  method="post" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{ form.as_p }}

        <button type="simbit">Авторизация</button>

    </form>
    <a href="/register/">Нет аккаунта?</a>

</center>

templates/prog_lang_detail.html
<p>Счетчик просмотров: {{ prog_id.views }}</p>
<p>{{ prog_id.title }}</p>
<p>{{ prog_id.description }}</p>
<img src="{{ prog_id.image.url }}" alt="" width="300" height="400">
<p>{{ prog_id.created_date_lang }}</p>
<a href="{{ prog_id.viki_url }}" target="_blank">Перейти на википедию</a>
<a href="{{ prog_id.file_python.url }}" download="скачанный файл ">Файл языка</a>
<p>{{ prog_id.created_at }}</p>

templates/prog_languages.html
<center>

<button><a href="{% url 'yaziki:sozdat_blog' %}">Добавить</a></button>

<br><br>

<form action="/search/" method="GET">
    <input type="text" type="search" name="s" placeholder="Найти язык программирования">
    <button type="submit">Найти</button>
</form>


{% for i in prog_lang %}

<h1>{{ i.title }}</h1>
<p> <a href="/prog_lang/{{ i.id }}/">Подробнее</a></p>

<p> <a href="/prog_lang/{{ i.id }}/delete/">Удалить</a> </p>
<p> <a href="/prog_lang/{{ i.id }}/update/">Редактировать</a> </p>
{% endfor %}


<div class="pagination">
        <span class="step-links">
            {% if prog_lang.has_previous %}
                <a href="?page=1">&laquo; Первая</a>
                <a href="?page={{ prog_lang.previous_page_number }}">Предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ prog_lang.number }} из {{ prog_lang.paginator.num_pages }}.
            </span>

            {% if prog_lang.has_next %}
                <a href="?page={{ prog_lang.next_page_number }}">Следующая</a>
                <a href="?page={{ prog_lang.paginator.num_pages }}">Последняя &raquo;</a>
            {% endif %}
        </span>
    </div>

<form action="{%  url 'login'  %}" method="post">
    {%  csrf_token  %}
    <button type="submit">Выйти из аккаунта</button>
</form> 


</center>

templates/register.html
<center>
    <h1>Регистрация</h1>
    <form  method="post" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{ form.as_p }}

        <button type="simbit">Регистрация</button>

    </form>
</center>

templates/relation_db.html
<h1>Cписок всех мащин с тегами</h1>
{% for i in number_car %}

<p>{{ i.nameCar }}</p>

<p>Теги:</p>
    {% for j in i.tags.all %}
    <p>#{{ j.name }}</p>
    {% endfor %}
    
<hr><hr><hr><hr>

<p>Комменты:</p>
{% for k in i.review.all %}

<p>{{ k.marks }}</p>
<p>{{ k.text }}</p>
<p>{{ k.created_at }}</p>

{% endfor %}

{% endfor %}

templates/update_prog_lang.html
<center>
    <h1>Добавить язык програмирование</h1>
    <form method="post" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{ form.as_p }}

        <button type="simbit">Изменить</button>

    </form>
</center>